export const SCREEN_NAMES = {
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  SUBSCRIPTION_SCREEN: 'SUBSCRIPTION_SCREEN',
  SAVED_DASHBOARD_SCREEN: 'SAVED_DASHBOARD_SCREEN',
  CREATE_DASHBOARD_SCREEN: 'CREATE_DASHBOARD_SCREEN',
  PROFILE_DASHBOARD_SCREEN: 'PROFILE_DASHBOARD_SCREEN',
};

export const STACK_NAMES = {
  CREATE_STACK: 'CREATE_STACK',
  PROFILE_STACK: 'PROFILE_STACK',
  SAVED_STACK: 'SAVED_STACK',
};

