export const SCREEN_NAMES = {
  HOME_SCREEN: 'HOME_SCREEN',
  SUBSCRIPTION_SCREEN: 'SUBSCRIPTION_SCREEN',
  DASHBOARD_SCREEN: 'DASHBOARD_SCREEN',
  RECORDING_SCREEN: 'RECORDING_SCREEN',
  AUDIO_RESULT_SCREEN: 'AUDIO_RESULT_SCREEN',
  HOME_LOADING_SCREEN: 'HOME_LOADING_SCREEN',
};

export const STACK_NAMES = {
  HOME_STACK: 'HOME_STACK',
  SETTING_STACK: 'SETTING_STACK',
};

